// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdq7_R29z00lqo_UhqycRk9GhY0arRco',
    appId: '1:607339416806:web:477947234b913b8c76bf27',
    messagingSenderId: '607339416806',
    projectId: 'digid-14afe',
    authDomain: 'digid-14afe.firebaseapp.com',
    storageBucket: 'digid-14afe.appspot.com',
    measurementId: 'G-23KV9FP02G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhlhgKomr-OF5XpIC0dlqrVFcrIYnlHvc',
    appId: '1:607339416806:android:63d26d75d37104c276bf27',
    messagingSenderId: '607339416806',
    projectId: 'digid-14afe',
    storageBucket: 'digid-14afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO5Klh_ui1dVahFVAhHnHBxx3U4PXNUHg',
    appId: '1:607339416806:ios:615bdcfc8edfde2876bf27',
    messagingSenderId: '607339416806',
    projectId: 'digid-14afe',
    storageBucket: 'digid-14afe.appspot.com',
    iosBundleId: 'com.example.digitalId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO5Klh_ui1dVahFVAhHnHBxx3U4PXNUHg',
    appId: '1:607339416806:ios:089f3eb012b2f94676bf27',
    messagingSenderId: '607339416806',
    projectId: 'digid-14afe',
    storageBucket: 'digid-14afe.appspot.com',
    iosBundleId: 'com.example.digitalId.RunnerTests',
  );
}
